=== MarginallyClever/Arm3/twl/TWL/src/de/matthiasmann/twl/theme/theme.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    PUBLIC ID  : -//www.matthiasmann.de//TWL-Theme//EN
    SYSTEM ID  : http://hg.l33tlabs.org/twl/raw-file/tip/src/de/matthiasmann/twl/theme/theme.dtd
-->

<!ELEMENT themes (images|fontDef|inputMapDef|theme|constantDef|include)*>

<!ELEMENT images (area|alias|composed|select|grid|animation|repeatImage|cursor|gradient)*>
<!ATTLIST images
    file    CDATA #IMPLIED
    format  CDATA #IMPLIED
    filter  CDATA #IMPLIED
    comment CDATA #IMPLIED>

<!ELEMENT area EMPTY>
<!ATTLIST area
    name            CDATA #IMPLIED
    xywh            CDATA #REQUIRED
    tiled           (true|false) #IMPLIED
    border          CDATA #IMPLIED
    tint            CDATA #IMPLIED
    inset           CDATA #IMPLIED
    repeatX         (true|false) #IMPLIED
    repeatY         (true|false) #IMPLIED
    sizeOverwriteH  CDATA #IMPLIED
    sizeOverwriteV  CDATA #IMPLIED
    nocenter        (true|false) #IMPLIED
    splitx          CDATA #IMPLIED
    splity          CDATA #IMPLIED
    center          (true|false) #IMPLIED
    rot             (0|90|180|270) #IMPLIED
    if              CDATA #IMPLIED
    unless          CDATA #IMPLIED>

<!ELEMENT alias EMPTY>
<!ATTLIST alias
    name            CDATA #IMPLIED
    ref             CDATA #REQUIRED
    tint            CDATA #IMPLIED
    border          CDATA #IMPLIED
    inset           CDATA #IMPLIED
    repeatX         (true|false) #IMPLIED
    repeatY         (true|false) #IMPLIED
    sizeOverwriteH  CDATA #IMPLIED
    sizeOverwriteV  CDATA #IMPLIED
    center          (true|false) #IMPLIED
    if              CDATA #IMPLIED
    unless          CDATA #IMPLIED>

<!ELEMENT composed (area|alias|composed|select|grid|animation|gradient)*>
<!ATTLIST composed
    name            CDATA #IMPLIED
    tint            CDATA #IMPLIED
    border          CDATA #IMPLIED
    inset           CDATA #IMPLIED
    repeatX         (true|false) #IMPLIED
    repeatY         (true|false) #IMPLIED
    sizeOverwriteH  CDATA #IMPLIED
    sizeOverwriteV  CDATA #IMPLIED
    center          (true|false) #IMPLIED
    if              CDATA #IMPLIED
    unless          CDATA #IMPLIED>

<!ELEMENT select (area|alias|composed|select|grid|animation|gradient)*>
<!ATTLIST select
    name            CDATA #IMPLIED
    tint            CDATA #IMPLIED
    border          CDATA #IMPLIED
    inset           CDATA #IMPLIED
    repeatX         (true|false) #IMPLIED
    repeatY         (true|false) #IMPLIED
    sizeOverwriteH  CDATA #IMPLIED
    sizeOverwriteV  CDATA #IMPLIED
    center          (true|false) #IMPLIED
    if              CDATA #IMPLIED
    unless          CDATA #IMPLIED>

<!ELEMENT grid (area|alias|composed|select|grid|animation|gradient)*>
<!ATTLIST grid
    name            CDATA #IMPLIED
    weightsX        CDATA #REQUIRED
    weightsY        CDATA #REQUIRED
    tint            CDATA #IMPLIED
    border          CDATA #IMPLIED
    inset           CDATA #IMPLIED
    repeatX         (true|false) #IMPLIED
    repeatY         (true|false) #IMPLIED
    sizeOverwriteH  CDATA #IMPLIED
    sizeOverwriteV  CDATA #IMPLIED
    center          (true|false) #IMPLIED
    if              CDATA #IMPLIED
    unless          CDATA #IMPLIED>

<!ELEMENT animation (repeat|frame|frames)+>
<!ATTLIST animation
    name            CDATA #IMPLIED
    count           CDATA #IMPLIED
    timeSource      CDATA #REQUIRED
    tint            CDATA #IMPLIED
    border          CDATA #IMPLIED
    inset           CDATA #IMPLIED
    if              CDATA #IMPLIED
    unless          CDATA #IMPLIED
    frozenTime      CDATA #IMPLIED>
    
<!ELEMENT frame EMPTY>
<!ATTLIST frame
    ref             CDATA #REQUIRED
    duration        CDATA #REQUIRED
    tint            CDATA #IMPLIED
    zoom            CDATA #IMPLIED
    zoomX           CDATA #IMPLIED
    zoomY           CDATA #IMPLIED
    zoomCenterX     CDATA #IMPLIED
    zoomCenterY     CDATA #IMPLIED>

<!ELEMENT frames EMPTY>
<!ATTLIST frames
    duration        CDATA #REQUIRED
    count           CDATA #REQUIRED
    xywh            CDATA #REQUIRED
    offsetx         CDATA #IMPLIED
    offsety         CDATA #IMPLIED
    tint            CDATA #IMPLIED
    zoom            CDATA #IMPLIED
    zoomX           CDATA #IMPLIED
    zoomY           CDATA #IMPLIED
    zoomCenterX     CDATA #IMPLIED
    zoomCenterY     CDATA #IMPLIED>

<!ELEMENT repeat (repeat|frame)+>
<!ATTLIST repeat
    count           CDATA #IMPLIED>

<!ELEMENT gradient (stop)+>
<!ATTLIST gradient
    name            CDATA #IMPLIED
    type            (horizontal|vertical) #REQUIRED
    wrap            (scale|clamp|mirror|repeat) #IMPLIED>

<!ELEMENT stop EMPTY>
<!ATTLIST stop
    pos             CDATA #REQUIRED
    color           CDATA #IMPLIED>

<!ELEMENT cursor (#PCDATA)>
<!ATTLIST cursor
    name            CDATA #IMPLIED
    xywh            CDATA #IMPLIED
    hotSpotX        CDATA #IMPLIED
    hotSpotY        CDATA #IMPLIED
    imageRef        CDATA #IMPLIED
    ref             CDATA #IMPLIED>

<!ELEMENT include EMPTY>
<!ATTLIST include
    filename        CDATA #REQUIRED>

<!ELEMENT theme (param|theme)*>
<!ATTLIST theme
    name            CDATA #REQUIRED
    ref             CDATA #IMPLIED
    merge           (true|false) #IMPLIED
    allowWildcard   (true|false) #IMPLIED>

<!ELEMENT param (color|enum|string|font|fontDef|inputMap|inputMapDef|int|float|bool|border|dimension|gap|size|constant|image|cursor|list|map)>
<!ATTLIST param
    name            CDATA #REQUIRED>

<!ELEMENT color (#PCDATA)>
<!ELEMENT enum (#PCDATA)>
<!ELEMENT string (#PCDATA)>
<!ELEMENT font (#PCDATA)>
<!ELEMENT inputMap (#PCDATA)>
<!ELEMENT int (#PCDATA)>
<!ELEMENT float (#PCDATA)>
<!ELEMENT bool (#PCDATA)>
<!ATTLIST enum
    type            CDATA #IMPLIED>
<!ELEMENT border (#PCDATA)>
<!ELEMENT dimension (#PCDATA)>
<!ELEMENT gap (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT constant (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT list (color|enum|string|font|int|float|bool|dimension|gap|size|constant|image|cursor|list|map)*>
<!ELEMENT map (param)*>
<!ATTLIST map
    ref             CDATA #IMPLIED>

<!ELEMENT constantDef (color|enum|string|font|int|float|bool|dimension|constant|list|map)>
<!ATTLIST constantDef
    name            CDATA #REQUIRED
    merge           (true|false) #IMPLIED>

<!ELEMENT fontDef (fontParam)*>
<!ATTLIST fontDef
    name            CDATA #IMPLIED
    default         (true|false) #IMPLIED
    filename        CDATA #IMPLIED
    offsetX         CDATA #IMPLIED
    offsetY         CDATA #IMPLIED
    underlineOffset CDATA #IMPLIED
    underline       (true|false) #IMPLIED
    linethrough     (true|false) #IMPLIED
    color           CDATA #IMPLIED>

<!ELEMENT inputMapDef (action)*>
<!ATTLIST inputMapDef
    name            CDATA #IMPLIED
    ref             CDATA #IMPLIED
    merge           (true|false) #IMPLIED>

<!ELEMENT action (#PCDATA)>
<!ATTLIST action
    name            CDATA #REQUIRED>

<!ELEMENT fontParam EMPTY>
<!ATTLIST fontParam
    if              CDATA #IMPLIED
    unless          CDATA #IMPLIED
    offsetX         CDATA #IMPLIED
    offsetY         CDATA #IMPLIED
    underlineOffset CDATA #IMPLIED
    underline       (true|false) #IMPLIED
    linethrough     (true|false) #IMPLIED
    color           CDATA #IMPLIED>

=== MarginallyClever/Arm3/twl/TWLExamples/src/inventory/inventory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE themes PUBLIC "-//www.matthiasmann.de//TWL-Theme//EN" "http://hg.l33tlabs.org/twl/raw-file/tip/src/de/matthiasmann/twl/theme/theme.dtd">
<themes>

    <images file="../chat/chat.png" format="RGBA" filter="linear">
        <area name="white" xywh="1,1,1,1"/>
        <area name="tooltip.background" border="3" xywh="1,24,7,7" splitx="L3,R3" splity="T3,B3"/>
        <area name="evilframe.background" border="27,10,10,10" xywh="40,1,20,29" splitx="L5,R5" splity="T19,B5"/>
        
        <area name="-innerframe.background" splitx="2,3" splity="2,3" xywh="17,1,5,5"/>
        <select name="innerframe.background" border="2">
            <alias ref="-innerframe.background" if="disabled" tint="#888"/>
            <alias ref="-innerframe.background"/>
        </select>
        
        <composed name="itemslot.background" border="5" sizeOverwriteH="40" sizeOverwriteV="40">
            <alias ref="-innerframe.background"/>
            <alias ref="white" if="dropOk" tint="#80FFFFFF"/>
            <alias ref="white" if="dropBlocked" tint="#80FF0000"/>
        </composed>
    </images>

    <images file="../test/chaos_sphere_blue_800x600.png" format="RGB" filter="linear">
        <area name="background-image" xywh="0,0,800,600"/>
    </images>
    <images file="diamond.png">
        <area name="icon.green" xywh="3,0,28,31" center="true"/>
        <area name="icon.red" xywh="34,0,29,31" center="true"/>
        <area name="icon.blue" xywh="65,0,29,31" center="true"/>
        <area name="icon.yellow" xywh="97,0,28,31" center="true"/>
    </images>

    <include filename="../test/cursors.xml"/>

    <fontDef name="normal" filename="../test/font.fnt" color="white">
        <fontParam if="error" color="red"/>
        <fontParam if="disabled" color="gray"/>
        <fontParam if="textSelection" color="blue"/>
    </fontDef>
    <fontDef name="black" filename="../test/font.fnt" color="black"/>

    <fontDef name="button" filename="../test/font.fnt" color="white">
        <fontParam if="disabled" color="gray"/>
        <fontParam if="pressed" offsetX="1" offsetY="1"/>
    </fontDef>
    
    <inputMapDef name="-defaultInputMap">
        <action name="selectAll">ctrl A</action>
        <action name="cut">ctrl X</action>
        <action name="copy">ctrl C</action>
        <action name="paste">ctrl V</action>
    </inputMapDef>

    <theme name="-defaults">
        <param name="background"><image>none</image></param>
        <param name="overlay"><image>none</image></param>
        <param name="font"><font>normal</font></param>
        <param name="textAlignment"><enum type="alignment">left</enum></param>
        <param name="minWidth"><int>0</int></param>
        <param name="minHeight"><int>0</int></param>
        <param name="maxWidth"><int>0</int></param>
        <param name="maxHeight"><int>0</int></param>
        <param name="inputMap"><inputMap>-defaultInputMap</inputMap></param>
        <!-- a wildcard in the base theme allows to make a flat theme -->
        <theme name="" ref="*"/>
    </theme>

    <theme name="fpscounter" ref="-defaults" allowWildcard="true">
        <param name="tooltip"><string>Current FPS</string></param>
    </theme>

    <theme name="label" ref="-defaults" allowWildcard="true"/>
    
    <theme name="button" ref="-defaults" allowWildcard="true">
        <param name="background"><image>innerframe.background</image></param>
        <param name="border"><border>background.border</border></param>
        <param name="font"><font>button</font></param>
    </theme>
    
    <theme name="tooltipwindow" ref="-defaults">
        <param name="background"><image>tooltip.background</image></param>
        <param name="border"><border>5</border></param>
        <param name="fadeInTime"><int>0</int></param>
        <theme name="label" ref="-defaults">
            <param name="font"><font>black</font></param>
        </theme>
    </theme>

    <theme name="resizableframe" ref="-defaults" allowWildcard="true">
        <param name="background"><image>evilframe.background</image></param>
        <param name="border"><border>background.border</border></param>
        <param name="titleAreaTop"><int>1</int></param>
        <param name="titleAreaLeft"><int>8</int></param>
        <param name="titleAreaRight"><int>-8</int></param>
        <param name="titleAreaBottom"><int>15</int></param>
        <param name="hasCloseButton"><bool>false</bool></param>
        <param name="closeButtonX"><int>0</int></param>
        <param name="closeButtonY"><int>0</int></param>
        <param name="hasResizeHandle"><bool>false</bool></param>
        <param name="resizeHandleX"><int>0</int></param>
        <param name="resizeHandleY"><int>0</int></param>
        <param name="fadeColorInactive"><color>white</color></param>
        <param name="fadeDurationActivate"><int>0</int></param>
        <param name="fadeDurationDeactivate"><int>0</int></param>
        <param name="fadeDurationShow"><int>0</int></param>
        <param name="fadeDurationHide"><int>0</int></param>
        <param name="mouseCursor"><cursor>arrow.*</cursor></param>
        <theme name="title" ref="-defaults">
            <param name="textAlignment"><enum type="alignment">left</enum></param>
            <param name="font"><font>black</font></param>
        </theme>
        <theme name="closeButton" ref="-defaults"/>
        <theme name="resizeHandle" ref="-defaults"/>
    </theme>
    
    <theme name="inventorydemo" ref="-defaults">
        <param name="background"><image>background-image</image></param>
    </theme>

    <theme name="inventorypanel" ref="-defaults" allowWildcard="true">
        <param name="slotSpacing"><int>5</int></param>
    </theme>
    
    <theme name="itemslot" ref="-defaults" allowWildcard="true">
        <param name="background"><image>itemslot.background</image></param>
        <param name="border"><border>background.border</border></param>
        <param name="icons"><map>
            <param name=""><image>icon.*</image></param>
        </map></param>
    </theme>
    
</themes>

=== MarginallyClever/Arm3/twl/TWLExamples/src/login/login.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE themes PUBLIC "-//www.matthiasmann.de//TWL-Theme//EN" "http://hg.l33tlabs.org/twl/raw-file/tip/src/de/matthiasmann/twl/theme/theme.dtd">
<themes>

    <images file="../chat/chat.png" format="RGBA" filter="linear">
        <area name="tooltip.background" border="3" xywh="1,24,7,7" splitx="L3,R3" splity="T3,B3"/>
        <area name="evilframe.background" border="27,10,10,10" xywh="40,1,20,29" splitx="L5,R5" splity="T19,B5"/>
        
        <area name="-innerframe.background" splitx="2,3" splity="2,3" xywh="17,1,5,5"/>
        <select name="innerframe.background" border="2">
            <alias ref="-innerframe.background" if="disabled" tint="#888"/>
            <alias ref="-innerframe.background"/>
        </select>
        
        <area name="-editfield.cursor" xywh="1,1,1,1"/>
        <animation name="editfield.cursor" timeSource="keyboardFocus">
            <frame ref="-editfield.cursor" duration="500"/>
            <frame ref="none" duration="500"/>
        </animation>
        <area name="editfield.selection" tint="#E000FEFF" xywh="1,1,1,1"/>
    </images>

    <images file="../test/chaos_sphere_blue_800x600.png" format="RGB" filter="linear">
        <area name="background-image" xywh="0,0,800,600"/>
    </images>

    <include filename="../test/cursors.xml"/>

    <fontDef name="normal" filename="../test/font.fnt" color="white">
        <fontParam if="error" color="red"/>
        <fontParam if="disabled" color="gray"/>
        <fontParam if="textSelection" color="blue"/>
    </fontDef>
    <fontDef name="black" filename="../test/font.fnt" color="black"/>

    <fontDef name="button" filename="../test/font.fnt" color="white">
        <fontParam if="disabled" color="gray"/>
        <fontParam if="pressed" offsetX="1" offsetY="1"/>
    </fontDef>
    
    <inputMapDef name="-defaultInputMap">
        <action name="selectAll">ctrl A</action>
        <action name="cut">ctrl X</action>
        <action name="copy">ctrl C</action>
        <action name="paste">ctrl V</action>
    </inputMapDef>

    <theme name="-defaults">
        <param name="background"><image>none</image></param>
        <param name="overlay"><image>none</image></param>
        <param name="font"><font>normal</font></param>
        <param name="textAlignment"><enum type="alignment">left</enum></param>
        <param name="minWidth"><int>0</int></param>
        <param name="minHeight"><int>0</int></param>
        <param name="maxWidth"><int>0</int></param>
        <param name="maxHeight"><int>0</int></param>
        <param name="inputMap"><inputMap>-defaultInputMap</inputMap></param>
        <!-- a wildcard in the base theme allows to make a flat theme -->
        <theme name="" ref="*"/>
    </theme>

    <theme name="fpscounter" ref="-defaults" allowWildcard="true">
        <param name="tooltip"><string>Current FPS</string></param>
    </theme>

    <theme name="label" ref="-defaults" allowWildcard="true"/>
    
    <theme name="button" ref="-defaults" allowWildcard="true">
        <param name="background"><image>innerframe.background</image></param>
        <param name="border"><border>background.border</border></param>
        <param name="font"><font>button</font></param>
    </theme>
    
    <theme name="tooltipwindow" ref="-defaults">
        <param name="background"><image>tooltip.background</image></param>
        <param name="border"><border>5</border></param>
        <param name="fadeInTime"><int>0</int></param>
        <theme name="label" ref="-defaults">
            <param name="font"><font>black</font></param>
        </theme>
    </theme>

    <theme name="editfield" ref="-defaults" allowWildcard="true">
        <param name=""><image>editfield.*</image></param>
        <param name="background"><image>innerframe.background</image></param>
        <param name="border"><border>background.border</border></param>
        <param name="passwordChar"><int>0x25CF</int></param>
        <param name="maxWidth"><int>32767</int></param>
        <param name="columns"><int>20</int></param>
        <param name="mouseCursor"><cursor>cursor.text</cursor></param>
        <theme name="renderer" ref="-defaults"/>
        <param name="autocompletion-height"><int>150</int></param>
    </theme>

    <theme name="logindemo" ref="-defaults">
        <param name="background"><image>background-image</image></param>
    </theme>

    <theme name="login-panel" ref="-defaults" allowWildcard="true">
                    <param name="background"><image>evilframe.background</image></param>
                    <param name="border"><border>background.border</border></param>
        <param name="defaultGap"><dimension>5,5</dimension></param>
        <param name="smallGap"><dimension>8,8</dimension></param>
        <param name="mediumGap"><dimension>10,10</dimension></param>
        <param name="largeGap"><dimension>15,15</dimension></param>
        <param name="namedGaps"><map/></param>
    </theme>
</themes>

=== MarginallyClever/Arm3/twl/TWLExamples/src/actions/actiondemo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE themes PUBLIC "-//www.matthiasmann.de//TWL-Theme//EN" "http://hg.l33tlabs.org/twl/raw-file/tip/src/de/matthiasmann/twl/theme/theme.dtd">
<themes>

    <images file="../test/chaos_sphere_blue_800x600.png" format="RGB" filter="linear">
        <area name="background-image" xywh="0,0,800,600"/>
    </images>

    <include filename="../test/cursors.xml"/>

    <fontDef name="normal" filename="../test/font.fnt" color="white"/>
    <fontDef name="result" filename="../textarea/bigfont.fnt" color="yellow"/>

    <inputMapDef name="-defaultInputMap">
        <action name="selectAll">ctrl A</action>
        <action name="cut">ctrl X</action>
        <action name="copy">ctrl C</action>
        <action name="paste">ctrl V</action>
    </inputMapDef>

    <theme name="-defaults">
        <param name="background"><image>none</image></param>
        <param name="overlay"><image>none</image></param>
        <param name="font"><font>normal</font></param>
        <param name="textAlignment"><enum type="alignment">left</enum></param>
        <param name="minWidth"><int>0</int></param>
        <param name="minHeight"><int>0</int></param>
        <param name="maxWidth"><int>0</int></param>
        <param name="maxHeight"><int>0</int></param>
        <param name="inputMap"><inputMapDef/></param>
    </theme>

    <!-- no tooltips used -->
    <theme name="tooltipwindow" ref="-defaults"/>

    <theme name="actiondemo" ref="-defaults">
        <param name="background"><image>background-image</image></param>

        <param name="inputMap"><inputMapDef>
            <action name="left">A</action>
            <action name="back">S</action>
            <action name="right">D</action>
            <action name="forward">W</action>
            <action name="load">ctrl O</action>
            <action name="save">ctrl S</action>
        </inputMapDef></param>
        
        <theme name="fpscounter" ref="-defaults">
            <param name="tooltip"><string>Current FPS</string></param>
        </theme>

        <theme name="instructions" ref="-defaults">
            <param name="textAlignment"><enum type="alignment">center</enum></param>
        </theme>

        <theme name="result" ref="-defaults">
            <param name="font"><font>result</font></param>
            <param name="textAlignment"><enum type="alignment">center</enum></param>
        </theme>
    </theme>
</themes>

=== MarginallyClever/Arm3/twl/TWLExamples/src/bgtest/bgtest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE themes PUBLIC "-//www.matthiasmann.de//TWL-Theme//EN" "http://hg.l33tlabs.org/twl/raw-file/tip/src/de/matthiasmann/twl/theme/theme.dtd">
<themes>

    <images file="../test/simple.png" format="RGBA">
        <area name="white" xywh="24,4,1,1"/>
        <alias name="black" ref="white" tint="#000"/>

        <alias name="-grid.bar" ref="white" tint="#008" sizeOverwriteH="10" sizeOverwriteV="10"/>
        <alias name="-grid.none" ref="none" sizeOverwriteH="10" sizeOverwriteV="10"/>

        <grid name="-grid.base.cell" weightsX="1,0,1" weightsY="1,0,1">
            <alias ref="black"/>
            <alias ref="-grid.bar"/>
            <alias ref="black"/>
            <alias ref="-grid.bar"/>
            <alias ref="-grid.bar"/>
            <alias ref="-grid.bar"/>
            <alias ref="black"/>
            <alias ref="-grid.bar"/>
            <alias ref="black"/>
        </grid>
        <grid name="grid.base" weightsX="1,1,1,1" weightsY="1,1,1,1">
            <alias ref="-grid.base.cell"/>
            <alias ref="-grid.base.cell"/>
            <alias ref="-grid.base.cell"/>
            <alias ref="-grid.base.cell"/>
            <alias ref="-grid.base.cell"/>
            <alias ref="-grid.base.cell"/>
            <alias ref="-grid.base.cell"/>
            <alias ref="-grid.base.cell"/>
            <alias ref="-grid.base.cell"/>
            <alias ref="-grid.base.cell"/>
            <alias ref="-grid.base.cell"/>
            <alias ref="-grid.base.cell"/>
            <alias ref="-grid.base.cell"/>
            <alias ref="-grid.base.cell"/>
            <alias ref="-grid.base.cell"/>
            <alias ref="-grid.base.cell"/>
        </grid>

        <grid name="-grid.mask.cell" weightsX="1,0,1" weightsY="1,0,1">
            <alias ref="black"/>
            <alias ref="-grid.none"/>
            <alias ref="black"/>
            <alias ref="-grid.none"/>
            <alias ref="-grid.none"/>
            <alias ref="-grid.none"/>
            <alias ref="black"/>
            <alias ref="-grid.none"/>
            <alias ref="black"/>
        </grid>
        <grid name="grid.mask" weightsX="1,1,1,1" weightsY="1,1,1,1">
            <alias ref="-grid.mask.cell"/>
            <alias ref="-grid.mask.cell"/>
            <alias ref="-grid.mask.cell"/>
            <alias ref="-grid.mask.cell"/>
            <alias ref="-grid.mask.cell"/>
            <alias ref="-grid.mask.cell"/>
            <alias ref="-grid.mask.cell"/>
            <alias ref="-grid.mask.cell"/>
            <alias ref="-grid.mask.cell"/>
            <alias ref="-grid.mask.cell"/>
            <alias ref="-grid.mask.cell"/>
            <alias ref="-grid.mask.cell"/>
            <alias ref="-grid.mask.cell"/>
            <alias ref="-grid.mask.cell"/>
            <alias ref="-grid.mask.cell"/>
            <alias ref="-grid.mask.cell"/>
        </grid>
    </images>

    <fontDef name="normal" filename="../test/font.fnt" color="white">
        <fontParam if="error" color="red"/>
        <fontParam if="disabled" color="gray"/>
        <fontParam if="textSelection" color="blue"/>
    </fontDef>

    <inputMapDef name="-defaultInputMap">
        <action name="selectAll">ctrl A</action>
        <action name="cut">ctrl X</action>
        <action name="copy">ctrl C</action>
        <action name="paste">ctrl V</action>
    </inputMapDef>

    <theme name="-defaults">
        <param name="background"><image>none</image></param>
        <param name="overlay"><image>none</image></param>
        <param name="font"><font>normal</font></param>
        <param name="textAlignment"><enum type="alignment">left</enum></param>
        <param name="minWidth"><int>0</int></param>
        <param name="minHeight"><int>0</int></param>
        <param name="maxWidth"><int>0</int></param>
        <param name="maxHeight"><int>0</int></param>
        <param name="inputMap"><inputMap>-defaultInputMap</inputMap></param>
    </theme>

    <theme name="tooltipwindow" ref="-defaults">
        <param name="border"><border>5</border></param>
        <param name="fadeInTime"><int>0</int></param>
        <theme name="label" ref="-defaults">
            <param name="font"><font>normal</font></param>
        </theme>
    </theme>

    <theme name="backgroundtest" ref="-defaults">
        <param name="grid"><image>grid.*</image></param>

        <theme name="fpscounter" ref="-defaults">
            <param name="tooltip"><string>Current FPS</string></param>
        </theme>
        <theme name="label" ref="-defaults"/>
    </theme>
</themes>
