=== MarginallyClever/Arm3/twl/TWL/src/de/matthiasmann/twl/theme/theme.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    PUBLIC ID  : -//www.matthiasmann.de//TWL-Theme//EN
    SYSTEM ID  : http://hg.l33tlabs.org/twl/raw-file/tip/src/de/matthiasmann/twl/theme/theme.dtd
-->

<!ELEMENT themes (images|fontDef|inputMapDef|theme|constantDef|include)*>

<!ELEMENT images (area|alias|composed|select|grid|animation|repeatImage|cursor|gradient)*>
<!ATTLIST images
    file    CDATA #IMPLIED
    format  CDATA #IMPLIED
    filter  CDATA #IMPLIED
    comment CDATA #IMPLIED>

<!ELEMENT area EMPTY>
<!ATTLIST area
    name            CDATA #IMPLIED
    xywh            CDATA #REQUIRED
    tiled           (true|false) #IMPLIED
    border          CDATA #IMPLIED
    tint            CDATA #IMPLIED
    inset           CDATA #IMPLIED
    repeatX         (true|false) #IMPLIED
    repeatY         (true|false) #IMPLIED
    sizeOverwriteH  CDATA #IMPLIED
    sizeOverwriteV  CDATA #IMPLIED
    nocenter        (true|false) #IMPLIED
    splitx          CDATA #IMPLIED
    splity          CDATA #IMPLIED
    center          (true|false) #IMPLIED
    rot             (0|90|180|270) #IMPLIED
    if              CDATA #IMPLIED
    unless          CDATA #IMPLIED>

<!ELEMENT alias EMPTY>
<!ATTLIST alias
    name            CDATA #IMPLIED
    ref             CDATA #REQUIRED
    tint            CDATA #IMPLIED
    border          CDATA #IMPLIED
    inset           CDATA #IMPLIED
    repeatX         (true|false) #IMPLIED
    repeatY         (true|false) #IMPLIED
    sizeOverwriteH  CDATA #IMPLIED
    sizeOverwriteV  CDATA #IMPLIED
    center          (true|false) #IMPLIED
    if              CDATA #IMPLIED
    unless          CDATA #IMPLIED>

<!ELEMENT composed (area|alias|composed|select|grid|animation|gradient)*>
<!ATTLIST composed
    name            CDATA #IMPLIED
    tint            CDATA #IMPLIED
    border          CDATA #IMPLIED
    inset           CDATA #IMPLIED
    repeatX         (true|false) #IMPLIED
    repeatY         (true|false) #IMPLIED
    sizeOverwriteH  CDATA #IMPLIED
    sizeOverwriteV  CDATA #IMPLIED
    center          (true|false) #IMPLIED
    if              CDATA #IMPLIED
    unless          CDATA #IMPLIED>

<!ELEMENT select (area|alias|composed|select|grid|animation|gradient)*>
<!ATTLIST select
    name            CDATA #IMPLIED
    tint            CDATA #IMPLIED
    border          CDATA #IMPLIED
    inset           CDATA #IMPLIED
    repeatX         (true|false) #IMPLIED
    repeatY         (true|false) #IMPLIED
    sizeOverwriteH  CDATA #IMPLIED
    sizeOverwriteV  CDATA #IMPLIED
    center          (true|false) #IMPLIED
    if              CDATA #IMPLIED
    unless          CDATA #IMPLIED>

<!ELEMENT grid (area|alias|composed|select|grid|animation|gradient)*>
<!ATTLIST grid
    name            CDATA #IMPLIED
    weightsX        CDATA #REQUIRED
    weightsY        CDATA #REQUIRED
    tint            CDATA #IMPLIED
    border          CDATA #IMPLIED
    inset           CDATA #IMPLIED
    repeatX         (true|false) #IMPLIED
    repeatY         (true|false) #IMPLIED
    sizeOverwriteH  CDATA #IMPLIED
    sizeOverwriteV  CDATA #IMPLIED
    center          (true|false) #IMPLIED
    if              CDATA #IMPLIED
    unless          CDATA #IMPLIED>

<!ELEMENT animation (repeat|frame|frames)+>
<!ATTLIST animation
    name            CDATA #IMPLIED
    count           CDATA #IMPLIED
    timeSource      CDATA #REQUIRED
    tint            CDATA #IMPLIED
    border          CDATA #IMPLIED
    inset           CDATA #IMPLIED
    if              CDATA #IMPLIED
    unless          CDATA #IMPLIED
    frozenTime      CDATA #IMPLIED>
    
<!ELEMENT frame EMPTY>
<!ATTLIST frame
    ref             CDATA #REQUIRED
    duration        CDATA #REQUIRED
    tint            CDATA #IMPLIED
    zoom            CDATA #IMPLIED
    zoomX           CDATA #IMPLIED
    zoomY           CDATA #IMPLIED
    zoomCenterX     CDATA #IMPLIED
    zoomCenterY     CDATA #IMPLIED>

<!ELEMENT frames EMPTY>
<!ATTLIST frames
    duration        CDATA #REQUIRED
    count           CDATA #REQUIRED
    xywh            CDATA #REQUIRED
    offsetx         CDATA #IMPLIED
    offsety         CDATA #IMPLIED
    tint            CDATA #IMPLIED
    zoom            CDATA #IMPLIED
    zoomX           CDATA #IMPLIED
    zoomY           CDATA #IMPLIED
    zoomCenterX     CDATA #IMPLIED
    zoomCenterY     CDATA #IMPLIED>

<!ELEMENT repeat (repeat|frame)+>
<!ATTLIST repeat
    count           CDATA #IMPLIED>

<!ELEMENT gradient (stop)+>
<!ATTLIST gradient
    name            CDATA #IMPLIED
    type            (horizontal|vertical) #REQUIRED
    wrap            (scale|clamp|mirror|repeat) #IMPLIED>

<!ELEMENT stop EMPTY>
<!ATTLIST stop
    pos             CDATA #REQUIRED
    color           CDATA #IMPLIED>

<!ELEMENT cursor (#PCDATA)>
<!ATTLIST cursor
    name            CDATA #IMPLIED
    xywh            CDATA #IMPLIED
    hotSpotX        CDATA #IMPLIED
    hotSpotY        CDATA #IMPLIED
    imageRef        CDATA #IMPLIED
    ref             CDATA #IMPLIED>

<!ELEMENT include EMPTY>
<!ATTLIST include
    filename        CDATA #REQUIRED>

<!ELEMENT theme (param|theme)*>
<!ATTLIST theme
    name            CDATA #REQUIRED
    ref             CDATA #IMPLIED
    merge           (true|false) #IMPLIED
    allowWildcard   (true|false) #IMPLIED>

<!ELEMENT param (color|enum|string|font|fontDef|inputMap|inputMapDef|int|float|bool|border|dimension|gap|size|constant|image|cursor|list|map)>
<!ATTLIST param
    name            CDATA #REQUIRED>

<!ELEMENT color (#PCDATA)>
<!ELEMENT enum (#PCDATA)>
<!ELEMENT string (#PCDATA)>
<!ELEMENT font (#PCDATA)>
<!ELEMENT inputMap (#PCDATA)>
<!ELEMENT int (#PCDATA)>
<!ELEMENT float (#PCDATA)>
<!ELEMENT bool (#PCDATA)>
<!ATTLIST enum
    type            CDATA #IMPLIED>
<!ELEMENT border (#PCDATA)>
<!ELEMENT dimension (#PCDATA)>
<!ELEMENT gap (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT constant (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT list (color|enum|string|font|int|float|bool|dimension|gap|size|constant|image|cursor|list|map)*>
<!ELEMENT map (param)*>
<!ATTLIST map
    ref             CDATA #IMPLIED>

<!ELEMENT constantDef (color|enum|string|font|int|float|bool|dimension|constant|list|map)>
<!ATTLIST constantDef
    name            CDATA #REQUIRED
    merge           (true|false) #IMPLIED>

<!ELEMENT fontDef (fontParam)*>
<!ATTLIST fontDef
    name            CDATA #IMPLIED
    default         (true|false) #IMPLIED
    filename        CDATA #IMPLIED
    offsetX         CDATA #IMPLIED
    offsetY         CDATA #IMPLIED
    underlineOffset CDATA #IMPLIED
    underline       (true|false) #IMPLIED
    linethrough     (true|false) #IMPLIED
    color           CDATA #IMPLIED>

<!ELEMENT inputMapDef (action)*>
<!ATTLIST inputMapDef
    name            CDATA #IMPLIED
    ref             CDATA #IMPLIED
    merge           (true|false) #IMPLIED>

<!ELEMENT action (#PCDATA)>
<!ATTLIST action
    name            CDATA #REQUIRED>

<!ELEMENT fontParam EMPTY>
<!ATTLIST fontParam
    if              CDATA #IMPLIED
    unless          CDATA #IMPLIED
    offsetX         CDATA #IMPLIED
    offsetY         CDATA #IMPLIED
    underlineOffset CDATA #IMPLIED
    underline       (true|false) #IMPLIED
    linethrough     (true|false) #IMPLIED
    color           CDATA #IMPLIED>

=== MarginallyClever/Arm3/twl/TWLExamples/src/keyevents/ListKeyEvents.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE themes PUBLIC "-//www.matthiasmann.de//TWL-Theme//EN" "http://hg.l33tlabs.org/twl/raw-file/tip/src/de/matthiasmann/twl/theme/theme.dtd">
<themes>

    <images file="../chat/chat.png" format="RGBA" filter="linear">
        <area name="tooltip.background" border="3" xywh="1,24,7,7" splitx="L3,R3" splity="T3,B3"/>
        <select name="vscrollbar.upbutton.background" center="true">
            <area tint="#FF0000" if="pressed" xywh="16,7,7,4"/>
            <area tint="#5A5A5A" xywh="16,7,7,4"/>
        </select>
        <select name="vscrollbar.downbutton.background" center="true">
            <area tint="#FF0000" if="pressed" xywh="16,12,7,4"/>
            <area tint="#5A5A5A" xywh="16,12,7,4"/>
        </select>
        <select name="vscrollbar.thumb.background">
            <area splity="4,5" tint="#FF0000" if="pressed" xywh="16,17,7,10"/>
            <area splity="4,5" tint="#5A5A5A" xywh="16,17,7,10"/>
        </select>
        <area name="innerframe.background" splitx="2,3" splity="2,3" border="2" xywh="17,1,5,5"/>
        
        <gradient name="white" type="horizontal" wrap="scale">
            <stop color="white" pos="0"/>
        </gradient>
        
        <animation name="anim" timeSource="now" sizeOverwriteH="12"  sizeOverwriteV="12">
            <frame ref="white" tint="red" duration="500"/>
            <frame ref="white" tint="blue" duration="500"/>
        </animation>
    </images>

    <images file="../test/chaos_sphere_blue_800x600.png" format="RGB" filter="linear">
        <area name="background-image" xywh="0,0,800,600"/>
        
        <composed name="background-anim">
            <alias ref="background-image"/>
            <grid weightsX="1,0" weightsY="0,1">
                <alias ref="none"/>
                <alias ref="anim"/>
                <alias ref="none"/>
                <alias ref="none"/>
            </grid>
        </composed>
    </images>

    <fontDef name="normal" filename="../textarea/code.fnt" color="white"/>
    <fontDef name="black" filename="../textarea/code.fnt" color="black"/>

    <inputMapDef name="-defaultInputMap">
        <action name="selectAll">ctrl A</action>
        <action name="cut">ctrl X</action>
        <action name="copy">ctrl C</action>
        <action name="paste">ctrl V</action>
    </inputMapDef>

    <theme name="-defaults">
        <param name="background"><image>none</image></param>
        <param name="overlay"><image>none</image></param>
        <param name="font"><font>normal</font></param>
        <param name="textAlignment"><enum type="alignment">left</enum></param>
        <param name="minWidth"><int>0</int></param>
        <param name="minHeight"><int>0</int></param>
        <param name="maxWidth"><int>0</int></param>
        <param name="maxHeight"><int>0</int></param>
        <param name="inputMap"><inputMap>-defaultInputMap</inputMap></param>
    </theme>

    <theme name="tooltipwindow" ref="-defaults">
        <param name="background"><image>tooltip.background</image></param>
        <param name="border"><border>5</border></param>
        <param name="fadeInTime"><int>0</int></param>
        <theme name="label" ref="-defaults">
            <param name="font"><font>black</font></param>
        </theme>
    </theme>

    <theme name="vscrollbar" ref="-defaults" allowWildcard="true">
        <theme name="upbutton" ref="-defaults">
            <param name=""><image>vscrollbar.upbutton.*</image></param>
            <param name="minHeight"><int>9</int></param>
        </theme>
        <theme name="downbutton" ref="-defaults">
            <param name=""><image>vscrollbar.downbutton.*</image></param>
            <param name="minHeight"><int>9</int></param>
        </theme>
        <theme name="thumb" ref="-defaults">
            <param name=""><image>vscrollbar.thumb.*</image></param>
        </theme>
        <param name="scaleThumb"><bool>true</bool></param>
        <param name="minWidth"><int>9</int></param>
        <param name="minHeight"><int>48</int></param>
    </theme>

    <theme name="hscrollbar" ref="-defaults">
        <!-- dummy -->
        <theme name="leftbutton" ref="-defaults"/>
        <theme name="rightbutton" ref="-defaults"/>
        <theme name="thumb" ref="-defaults"/>
        <param name="scaleThumb"><bool>false</bool></param>
    </theme>

    <theme name="scrollpane" ref="-defaults">
        <theme name="hscrollbar" ref="hscrollbar"/>  <!-- not used -->
        <theme name="vscrollbar" ref="vscrollbar"/>
        <param name="minWidth"><int>100</int></param>
        <param name="minHeight"><int>100</int></param>
        <param name="maxWidth"><int>32767</int></param>
        <param name="maxHeight"><int>32767</int></param>
        <param name="hasDragButton"><bool>false</bool></param>
        <param name="autoScrollArea"><int>5</int></param>
        <param name="autoScrollSpeed"><int>10</int></param>
        <param name="scrollbarsAlwaysVisible"><bool>true</bool></param>
    </theme>

    <theme name="listkeyevents" ref="-defaults">
        <param name="background"><image>background-anim</image></param>
            
        <theme name="scrollpane"  ref="scrollpane">
            <param name="background"><image>innerframe.background</image></param>
            <param name="border"><border>background.border</border></param>

            <theme name="textarea" ref="-defaults">
                <param name="fonts"><map>
                    <param name="default"><font>normal</font></param>
                </map></param>
                <param name="images"><map/></param>
                <param name="classes"><map/></param>
                <theme name="image" ref="-defaults"/>
            </theme>
        </theme>
    </theme>
    
</themes>
